import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router';

export default function User() {
  const router = useRouter();
  const { ID } = router.query;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        user.tsx <br />
        {ID}
      </main>
    </>
  )
}
