import { TProps } from '@/types';
import { GetServerSideProps } from 'next';
import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router';
import { useEffect } from 'react';

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {

  return {
      props: {
        /* user: {
          
        } */
      }
  };
}

export default function Home({ user }: TProps) {

  const router = useRouter();

  useEffect(() => {
    if(!user) router.push("/auth");
  })

  return (
    <>
      <Head>
        <title>CatchMe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <p>index.tsx</p>
      </main>
    </>
  )
}
